// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_R1IlX_IKTFQQ8Vn8AEx4qQKFzu6qpC8',
    appId: '1:54234456855:web:7d481885e07dfafb2f0d52',
    messagingSenderId: '54234456855',
    projectId: 'careem-clone-app',
    authDomain: 'careem-clone-app.firebaseapp.com',
    storageBucket: 'careem-clone-app.appspot.com',
    measurementId: 'G-GK9B97S00R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG6AL7tQ5leBgEIOog_7VCxOmUUFxMC8k',
    appId: '1:54234456855:android:bbb34045a6a644ed2f0d52',
    messagingSenderId: '54234456855',
    projectId: 'careem-clone-app',
    storageBucket: 'careem-clone-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaaqdMWC1o_9VzZFgxGpkE0fQMdj4wFu0',
    appId: '1:54234456855:ios:703b01b4a086770c2f0d52',
    messagingSenderId: '54234456855',
    projectId: 'careem-clone-app',
    storageBucket: 'careem-clone-app.appspot.com',
    iosClientId: '54234456855-ocph98jfs6t8q7ovbslbvaav1plql92m.apps.googleusercontent.com',
    iosBundleId: 'com.example.careemClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaaqdMWC1o_9VzZFgxGpkE0fQMdj4wFu0',
    appId: '1:54234456855:ios:5689ae38f106890b2f0d52',
    messagingSenderId: '54234456855',
    projectId: 'careem-clone-app',
    storageBucket: 'careem-clone-app.appspot.com',
    iosClientId: '54234456855-emokv26r638nkikeu3ofsp2a88e8be49.apps.googleusercontent.com',
    iosBundleId: 'com.example.careemClone.RunnerTests',
  );
}
